parameters:
#    gg_team_front.example.class: GGTeam\FrontBundle\Example

services:
#    gg_team_front.example:
#        class: %gg_team_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
