shorty_homepage:
    pattern:  /
    defaults: { _controller: ShortyFirstBundle:Default:index }

shorty_add:
    pattern: /add
    defaults: { _controller: ShortyFirstBundle:Default:add }
    methods: [GET,POST]
