parameters:
    shorty_first.slug_generator.class: Shorty\FirstBundle\Services\SlugGenerator
    shorty_first.sha1.class: Shorty\FirstBundle\Services\Sha1

services:
    shorty_first.slug_generator:
        class: %shorty_first.slug_generator.class%
        arguments: ["@shorty_first.sha1"]
    shorty_first.sha1:
        class: %shorty_first.sha1.class%
